### ISSUE TITLE
Killer Knive bugfix suggestion

### ISSUE THREAD

**Issue by UpcraftLP** [LuckyCrew/Halloween#1]
the killer knive only checks for the target entity's look vector [this line](https://github.com/LuckyCrew/Halloween/blob/0203e45dbcd69146920b686a08a91df667736962/src/main/java/de/luckycrew/halloween/listener/ListenerKillerKniveAttack.java#L29), you should check against the body rotation vector instead.

also you should really move that to the item class instead of using the event since it's your own item.

**Comment by HyCraftHD** [comment]
Thanks for the suggestion. I'll try it.
Moving this to item class will be done in updates, even if this doesn't change something.
